# Generated by Django 5.1.7 on 2025-06-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_url', models.URLField(help_text='URL del GIF animado')),
            ],
        ),
    ]
