# Generated by Django 5.1.7 on 2025-06-16 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignada_el', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to='usuarios.cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.rutina')),
            ],
        ),
    ]
