# Generated by Django 5.1.7 on 2025-06-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rutinaasignada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutinaasignada',
            name='completada',
        ),
        migrations.AlterField(
            model_name='rutinaasignada',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='usuarios.cliente'),
        ),
    ]
