# Generated by Django 5.1.7 on 2025-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaasignada',
            name='completada_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
