# Generated by Django 5.1.7 on 2025-07-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinaasignada',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
