# Generated by Django 5.1.7 on 2025-07-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_rutinaasignada_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='altura',
            new_name='Altura',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='edad',
            new_name='Edad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='genero',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='peso',
            new_name='Peso',
        ),
    ]
